version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python app/manage.py makemigrations &&
             python app/manage.py migrate &&
             python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
  redis:
    image: redis:7
  celery:
    build: .
    command: celery -A backend worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
      - web

  celery-beat:
    build: .
    command: celery -A backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
      - web  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: subscriptiondb
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
