# Generated by Django 5.2.4 on 2025-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeratelog',
            name='base_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
