# Generated by Django 5.2.4 on 2025-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exchangeratelog_base_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeratelog',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='exchangeratelog',
            name='base_value',
        ),
        migrations.RemoveField(
            model_name='exchangeratelog',
            name='target_currency',
        ),
        migrations.AddField(
            model_name='exchangeratelog',
            name='base',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='exchangeratelog',
            name='target',
            field=models.CharField(default='BDT', max_length=3),
        ),
    ]
