# Generated by Django 5.2.4 on 2025-08-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exchangeratelog_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('base_amount', models.FloatField()),
                ('target_amount', models.FloatField()),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
    ]
