# Generated by Django 5.2.4 on 2025-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.AlterField(
            model_name='exchangeratelog',
            name='base',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exchangeratelog',
            name='fetched_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exchangeratelog',
            name='target',
            field=models.CharField(max_length=10),
        ),
    ]
