# Generated by Django 5.2.4 on 2025-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_exchangerate_alter_exchangeratelog_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeratelog',
            name='base',
        ),
        migrations.RemoveField(
            model_name='exchangeratelog',
            name='target',
        ),
        migrations.AddField(
            model_name='exchangeratelog',
            name='base_currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exchangeratelog',
            name='target_currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
